version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: myproject_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env     # create this on server or generate from Jenkins secrets
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    container_name: myproject_frontend
    restart: unless-stopped
    ports:
      - "80:80"

  admin:
    build:
      context: ./admin
    container_name: myproject_admin
    restart: unless-stopped
    ports:
      - "8081:80"
